### ISSUE TITLE
Estimate of Release?

### ISSUE THREAD

**Issue by mjsisley** [airbnb/hypernova-client#1]
Thanks for open sourcing hypernova!

Is there a rough estimate of when the testing suite will be made available?

**Comment by goatslacker** [comment]
Testing suite?

**Comment by mjsisley** [comment]
This repo has "Placeholder for future test suite to validate hypernova clients." in the readme. Just wondering if/when that is coming.

**Comment by goatslacker** [comment]
Oh, sorry I wasn't aware of this repo.

I think this stems from this issue: https://github.com/airbnb/hypernova/issues/9

**Comment by ljharb** [comment]
https://github.com/airbnb/hypernova/issues/9#issuecomment-239264818
